# Prerequisites:
# - Disable MFA on EntraID : Go to EntraID > Properties > Disable Default security
# - Add API autorizations on Enterprise Application with Admin consent on: 
#   - Microsoft Graph > Delegated autorizations > user.read openid profile offline_access

@AzureEntraIdBaseUrl = https://login.microsoftonline.com
@TenantId = <TenantId>

POST {{AzureEntraIdBaseUrl}}/{{TenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type=password
&client_id=<Client_Id>
&client_secret=<Client_Secret>
&scope=user.read openid profile offline_access
&username=<Email>
&password=<Password>

###
