# Prerequisites:
# - Disable MFA on EntraID : Go to EntraID > Properties > Disable Default security
# - Add API autorizations on Enterprise Application with Admin consent on: 
#   - Microsoft Graph > Delegated autorizations > user.read openid profile offline_access
# - If assertion are added don't forget to "acceptMappedClaims": true to manifest

@AzureEntraIdBaseUrl = https://login.microsoftonline.com
@TenantId = tenantId
@GrantType = password
@ClientId = clientIdToChange
@ClientSecret = ClientSecret
@Scope = user.read openid profile offline_access
@Username = Username@microsoft.com 
@Password = password

# Curl
#
# curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
# -d "client_id=<CLIENT_ID>&scope=https%3A%2F%2Fgraph.microsoft.com%2F.default&client_secret=<CLIENT_SECRET>&grant_type=client_credentials" \
# "https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/token"
#
# curl -X POST -H "Content-Type: application/x-www-form-urlencoded" \
# -d "grant_type=password&client_id=<CLIENT_ID>&client_secret=<CLIENT_SECRET>&scope=<SCOPE>&username=<USERNAME>&password=<PASSWORD>" \
# "https://login.microsoftonline.com/<TENANT_ID>/oauth2/v2.0/token"


POST {{AzureEntraIdBaseUrl}}/{{TenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type={{GrantType}}
&client_id={{ClientId}}
&client_secret={{ClientSecret}}
&scope={{Scope}}
&username={{Username}}
&password={{Password}}

###

POST {{AzureEntraIdBaseUrl}}/{{TenantId}}/oauth2/v2.0/logout
Content-Type: application/x-www-form-urlencoded

###

GET https://jwt.io

###

