# Prerequisites:
# - Disable MFA on EntraID : Go to EntraID > Properties > Disable Default security
# - Add API autorizations on Enterprise Application with Admin consent on: 
#   - Microsoft Graph > Delegated autorizations > user.read openid profile offline_access
# - If assertion are added don't forget to "acceptMappedClaims": true to manifest

@AzureEntraIdBaseUrl = https://login.microsoftonline.com
@TenantId = tenantId
@GrantType = password
@ClientId = clientIdToChange
@ClientSecret = ClientSecret
@Scope = user.read openid profile offline_access
@Username = Username@microsoft.com 
@Password = password

POST {{AzureEntraIdBaseUrl}}/{{TenantId}}/oauth2/v2.0/token
Content-Type: application/x-www-form-urlencoded

grant_type={{GrantType}}
&client_id={{ClientId}}
&client_secret={{ClientSecret}}
&scope={{Scope}}
&username={{Username}}
&password={{Password}}

###

POST {{AzureEntraIdBaseUrl}}/{{TenantId}}/oauth2/v2.0/logout
Content-Type: application/x-www-form-urlencoded

###

GET https://jwt.io

###
